#----------------------------------------------------------------------
# This file was generated by encode_bitmaps.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

#----------------------------------------------------------------------
Smiles = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAolJ"
    "REFUOI1tk91Lk2EYxn/vx7OmwyBhVsytmY1cCBFBQWSRlYVGJ51EjajptliH4X/QQeJ5J+ZJ"
    "f0AnIVSWJ0EQQfQhzNG3JkRQILrl3tft6sDNRvnAdfI8z8V939d13Vi2w79IpS4pHt8p17Vk"
    "jK1EIqpcLqPN/to0nWwmrc5IUL29n3jw4Ajl8mVKpYvcv7+frq5HdEZqymauqZljWbYDwOlT"
    "xxSL/eTOnfMY4wElYAWoAhXgI75fIJ/3mJ8/wvST5xaw3kE2k1YsBhMTtzEmCYTqxEaxVaCM"
    "MRYTE1uIxZ6RzVxdf7Rsh2i0XZ5XkPRF0mONjo4KkJSSlBKgcDgsqVVSizwPRTuRZTu42Uxa"
    "XV1rGNMCOECN8fHxpimX6OnpYW5uDmgF1TAEuXG9yuf5lOyZmYcMDUWAReAj8LqJXAEWWVhY"
    "aLqrQaWVoZNtzMxMYRljq1S6iTFtwCrDw9+ZnPQ2hIOFuqB1crUKSx34qw6hXfMNG7264stM"
    "TvrAEvAOKDaRBVpjd2cQ/BbwgwDY8XiEYvEb8AMokky+BF7UK+svGR+qNp+/L0O5jeKcRXxX"
    "GLe//wxTU/fo7Q0AolCAUEiUGoWpAWtQtTi4rw19iUB5K1OPf9F//GTDRkue11K3ad0qBYMK"
    "BAJyXUehoKv93e3S4l6p0Cfv1QlFdwS0EeXBwTT5/Op6mw389qn4Pr5jcTjZweunUVgOw1qA"
    "/K0ig2fOsREky3YYGOjTyAjyPCTVUbWllW3St6T04ZC8N0c1cmGHBo4f0H/LNP3kueU4w3R3"
    "w9gYzM6CX3HwKzaz71cYu/uV7rMvcLb2Mf3srbURi81WNJdLK5HYLuMi46LEng7lMlc2Xec/"
    "xiMt8QU2mDwAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
_rt_alignleft = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAEJJ"
    "REFUOI1jZGRiZqAEMFGkm4GBgYWBgYHBx9vrPzmat2zdxshIqRdIcsGWrdsY0cXo6wJsLhoN"
    "g2ERBhRnJooNAACQdhhQZbXeGAAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
_rt_alignright = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAADxJ"
    "REFUOI1jZGRiZqAEMFGkm4GBgYWBgYHBx9vrPzmat2zdxshIqRdYsAkS6yLquWA0DEZ8GFCc"
    "mSg2AADQZxhQFG0xxgAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
_rt_bold = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAEtJ"
    "REFUOI3NUkEKACAMyq3//7jWNQwWY0HzKNOJCIi2DCSlfmHQmbA5zBNAFG4CPoAodo4fFOyA"
    "wZGvHTDqdwCecnQHh0EU/ztIGyy1dBRJuH/9MwAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
_rt_centre = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAEJJ"
    "REFUOI1jZGRiZqAEMFGkm4GBgYWBgYHBx9vrPzmat2zdxshIqRdYkDnEumTL1m2MMDZ1XDAa"
    "BiM+DCjOTBQbAAAwdhhQDziCqAAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
_rt_colour = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAPZJ"
    "REFUOI1jZGRiZqAEsOCS+Mcu9h+bONPPV4wofEKa37Lz4zWYEd0LuGzG5RKsLiAFDEIDllTz"
    "MWxtyGJ4yiWKofgfCyTSkGMCJRDd/hr/Z2BgYGCZ5cAg8v0jg++C9wy6zx8ysP37zfCYXYFh"
    "g1gww+VfUSiGwg2AaRZ/JcPw6v0fhv/qLxg4vv1jCOv5zPBvZgrDSukghp8/ZRkY/rFiGgDT"
    "jBV84mX4572WgekzL8O/v5hBxoRXMwMDw/+3QgwM/3CHNeFY+MvMwMDyE6vtRBnAKPqWgUH2"
    "OQUu4P/IwGh8HrcFBAORgYFhF/NZRhetP1jVAACsCFJPHjA77wAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
_rt_copy = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAPCAYAAADtc08vAAAABHNCSVQICAgIfAhkiAAAATlJ"
    "REFUKJGFk71OwzAURo/tpE2AdihiAAmQWNiKWICpDIhnQEi8A0+ASsXAzDsgIcTEA3QANsZu"
    "XTMQBiqkUkFF04aB2sRJSO90bV+f+33+EUIqzq7bMam471UA6JzuiPRaMqROltc2KS9tMFhY"
    "JVArAJw31qlfPWfguYCqp6j5Lou+S81XpmAWRGgLe1t13r8i+sMxYdAtasrFyYGx5eik4v11"
    "DYHW8T6dl0/6w4i3wYjXjxFh0KV51ADasYYYQNUzKXlQDQYsiNnluzLJA6CsBKQgrdtHa2x2"
    "zJdkeoq5koLvsYEc7m5bdqxqRwk8V5C4GFwlDCRKKdR2Egq01IkpUhJgCsmKtkdKJiHTOSFA"
    "xoWQ7NFbgF8F+ZAU4PLuKbMopYBJXAhxwH5ZgPW5ZkH+tdC8eShyZ+IHUNNZHhrzal0AAAAA"
    "SUVORK5CYII=")

#----------------------------------------------------------------------
_rt_cut = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAPCAYAAADtc08vAAAABHNCSVQICAgIfAhkiAAAAbBJ"
    "REFUKJGdk0FLG1EQx3/vpRdv7sG49CKYxvSmVDwkpd78ALbSShQkbU81guAH8BN4EE0KGlCQ"
    "5iAIoiaIwWAP3bi0WXZLW1q2WfGmJ8mhV19Pu+xqWsSBx/Bm/vObmQcPIWP4Jz83r96vb6pw"
    "LJxzXfdWThKyuJR8/2rjOI4Kxz8ZDQUwkHosuGERwOLKsohLydpaKSIqfyjfrOsM8C2VSlKr"
    "1RRAtVJRAK8mJ+8GWFxZFldui93dPTzvTFWqhwCMPnt6a3yAB52CWjLBSCLBwcH+P0f/7wpX"
    "bouLywvys+/uB9CSCfRendVCkezMm/tN8PnwiKHBQX59axKXHWUACCFjAHyp15VX2gIgbdg0"
    "MkO8LG+I7WxO+XeARwt5ngwPBw8q/eLe1wtI75y25QTCsG9bDtI7p+fFW6xmU0UAXmkLU9eY"
    "OK0LNf0cIOji+4ezOSZO68LUNX4vrUbfIG3YXPf3AdD9o4Wpa5E9TV3jT8MC4Lq/j7RhRwGm"
    "rtG2HPx9u6bGI4CuqXHShs12NqfalhNtIGSMn8cnaiczpnYyY6paKHb8jdVCMdA0Tz4Gmr9P"
    "zKg0oZ3GfwAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
_rt_font = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAIpJ"
    "REFUOI21k8ENgCAMRSmMpwzAgenUsgDMhweCgUpRJDYhJG362v8DAFKJmZBT3W8A67LFz4Bj"
    "T835HgY4V99DADqV24IF5Kk+WOht0QTkabm5twW03kHPeQoVIFV1EDFqjZHmtU55xLp2k8Bp"
    "NaZdrwCcdhqlF5cHVHcJ4TzxwULTxJH4/zM9xQmi7UCACkKFWgAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
_rt_idea = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAVtJ"
    "REFUWIXtl2FOwkAQhd8u3gAJp1EXuQEBrmOU24DxBtoWjmA8BAlXsOsPXNjadjtvRImJ708T"
    "pnS+fTudnRpjezinLjR/Wq5K//W3+cwazbMM40BIPJ3c1GKPT4UKRASQShxruyuwWYMC6QRY"
    "rkpfTZwBGCUhAGCzlkFYCeUxcTW5Ma521/Ay7RIFcFx9VouF5E0QAHB13VysFEBd7dbHYlxo"
    "BUitXgohcYFwQLZ6VoJGpE+834oieQ9ZA5zCK3kWAEnyJMB8Zk1or1pJmpHaAe/zylUrRSvu"
    "VjgTJK1YdRwD1Q4YuyDd+6DOLWBqgT2IAGIekGwFY30QVYQpJ+JZgJEYILUqzSASRBXh2+sd"
    "Bn3XGBv0gTzPASyYR/JvwT7J6UQDOOdaYxq4fwcogPuHhQHQOuF8xilRHyaxspfnA8jodqz6"
    "KvoWgC/fDwDG9n4f4FT60ZHsTwB8AA6FjDfFEDh8AAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
_rt_indentless = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAHRJ"
    "REFUOI3Nkm8KgCAMxfe2TlftCJ0u6ATa9eyTIqZiKdEDYfj25+eQwEKlo6qu5oOFABbq0eSD"
    "dZldbBh7Ir3LaSTB7ozdEJstBOyL3xJA9bgVpyTVBmAJBK1PMPYMefx0YpagR7/6B2WCeGnD"
    "CbhmfrKDC/GuLg9MR0atAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
_rt_indentmore = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAHlJ"
    "REFUOI3NkmEKgCAMhbfZ6aododMJncB5PftlTE2TkuiBID7f9jkEJAO1xcyh5SMZQCQDbzTF"
    "zbrMQRtOPOZnVxpJYIOTDbXZQ0BpwN4GciHzXoRykmaBOIPYXYdrT3DizzuUGv2dC4Kn+tU/"
    "qBPooQ0noJb5yQwOwa4uD/KzgEcAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
_rt_italic = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAGdJ"
    "REFUOI3Vk1EOgDAIQwt4/2P0lopfS6YOgsEfl+xntK8kMBE1dI623F8Atqzox+73N1GTcgez"
    "mOTDPEThJekAHIBHmhQwzCTfAyrpKaCSHgKq6SGgmi5qkHmVV3Nfzf5S+/9faANOrocplI0e"
    "xSoAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
_rt_open = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAPCAYAAADtc08vAAAABHNCSVQICAgIfAhkiAAAAbpJ"
    "REFUKJGlkz1IW1EUx39X3zNRgwFBMaCoQ0sFJwfpICgBccgkQQlOIUWE0lJCVTS0KWhU0KhY"
    "LeigoIMaQXCwgx9YR3XoIC2lpYMu4uLg0/jy8gLPQfLwGePimc79n3t+5+NyhcjJ5TkmPSbW"
    "BwaM++ejhbDICqjy9hoPxaOFsKgPDBirUQ8APjCyQSSAd54mi7hVUWZE/B583TGmwy9YjXqy"
    "QkR1W7/xEKBoOopyxXXihuPTc758dFDjasTdGTPvnKyPCoCcx9oqssmUlxTzqqI8Izb9oSNz"
    "BICZ7/uWQKnTYfqq8QdoBOD91DIAVd5eo7bSZX2Fr2992GUZm02mZ26NN8M/AbgAdpKD9H+D"
    "5rzPuDtj/F0Zwts3czeCoqoAxFWNhK6jaTpjXe3Mh+osXaWTfy2G2T74jbmDpb1DAi0NXN0k"
    "LJCIv9WEpJMPZ0Noeoq5jR9sTgSFOUKBJKFpuqWiXZaJ+Fv5FIKRyxg740GSqSSQZ13i65fV"
    "KKpKEfkZW09DnMWFxNW7Av9Oz6wAhz0XXUuhkB2SiCehEFBhcm2LzYmgAJCcBXZ2j/9nJD1l"
    "tZUu0xfP/Y230rSdugX3RssAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
_rt_paste = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAPCAYAAADtc08vAAAABHNCSVQICAgIfAhkiAAAAXNJ"
    "REFUKJGFkzsvREEYhp/vzDnWWHuxdnsJjd+wRKPYgkIUKqHVKtYlQoi4FX6BiGQTolEpFBIU"
    "/gUJtbXWdSMuo1jGHueceJvJN5nvmff9JiPiKH6UL5YMITrfGJWwfQARR5EvlsxY8pqr6gvL"
    "60u+A3NT8wCcOd2hICdfLJmT/k+AQPPPXke6hcP241CHbmOxtboW5TRS0jO9a06HM5j7MgAf"
    "lRsAzE2N15cLBm77A02NURxLSmUBUJlcvc5pYi1dAGxODDI7WgDgaHHEF8UBkERbJAQgrV2y"
    "rZ510AixM5BEG+bxDkllMfdlVCZn46T071MXFvZ9cVwAiScxzw+hEIAm5ZDSsD05RLX2Tvnp"
    "jZXS0S8AnUAgFALQ7AlQh/yVHSI6gcSTNo5vJiI0e/LtRJHWrh8gno6EAHhKLCTepHwzqaNi"
    "McRVmNpTIA5U6J3ZC3r3AZz6IroV3j8wYCFn4532cN/OZeA/uAC98weRN/ynL78NdulpYuMM"
    "AAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
_rt_redo = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAPCAYAAADtc08vAAAABHNCSVQICAgIfAhkiAAAAg5J"
    "REFUKJGdkr9rU1EcxT/3vbz2vfS924qRpmopVmIsFCWDiFkCAXHs5CDoJqSrJIP+BS5tXCw0"
    "EHDo4FBUguDgULVQImJJLe0Qu2hqWyKNMT9q0p/XofRHmtrBA9/l3HPPPffcK4Sms4fxyRn1"
    "NDXFYqG0z4Wv+kg+uC34B8SeQTSRUq/S87SbLU2iUn2D6/5unj+612AUTaSUEJpO/OV7Nfb2"
    "Mx5TA2B9W6OyuYVjuGjVdxq4zGhMHD5QCE0nFB1RHl1h6DrZ4hrhgI/+nk7mvueZyCzQK00M"
    "XadS32G5VuNyTydLywUqm1u4AMprNXxdkmp9m3DAx3BkoPHOg0PKf6qNrg4Dx9TYKJa45HEz"
    "vVJGA3AMF7bpxjZ1zp1pb+ogMxoT2eIaAN4Oh+7THdimG2A3AYCUDtK2SE3NH9u2bLOwTTdS"
    "OvucY6zuGlzrv0C1XuOsI/G0NL9YYHBIhXq9SMtqWtMAhiMDYjpXQNoWtwJ9hKIjak9w5/GY"
    "AljIr5L7XaBcqyFtC2lbiBbj4B/cfzKupLZN0H+RX+Uqzz5+JR2PNMQZn5xR2cU887mfLC0X"
    "+FH5c2AAcPNhQt290cf5Tg8r+SIjH+aaTJogNL1hgrGkejExq2az39Trd19UMJZURzWHRztq"
    "mI5HxPCbT6yW1rni7ybo954YwHUcmY5HRNxOKmm1nrgZaOzgf/AXUUy2DjrCDG0AAAAASUVO"
    "RK5CYII=")

#----------------------------------------------------------------------
_rt_save = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAPCAYAAADtc08vAAAABHNCSVQICAgIfAhkiAAAAQ1J"
    "REFUKJFjjE/L/c9AJlg0ZxojCwMDA8Oee78YvOzNGGbVJBHUFFc7hWHfiSsMLkpsDAwMDAws"
    "DAwMDPE+rgyvP39kYGBgYNi7bz9Ozc5Ojgww9U+vHUQYgE0RsQDDAGJcgNcAsl0gysvPEFc7"
    "haAGWRFJ3C5AlyTJBTCw7fxVvBq8DLVxG7Dt/FWG0kBLOF+In5eBn5eHgYeXl4Gfl49BTlKQ"
    "wTChCcUQDBcwMDAwlE1Zy6CppsrAwMDA0JTkjtdFTHhlGRgYfv3+x8D89wfD7z9/yDOA+d93"
    "hq9/WBh+/f2LVR7DC3KifAwrGhMZhKXkGTQVJAiZz8DIyMTMEJeSRXKOXDRnGiMDAwMDALeo"
    "P7cp9rvcAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
_rt_smiley = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAATpJ"
    "REFUWIXtV9EWwiAIRdeH7dP3Y0UPxiIHXjR31kO8VIPuvQNFTCkvdKXdRv7EjzvXz1Je0qkC"
    "NCkf6IlSevt7xCRUAiG2SH3QuJCMyJn7yIlKPLNdqtrMDIy8tU/w+nSy4WZgBrngtLJxECBp"
    "tyyBiiI/FIDImX0S5Pey0FyENbgA1STI3xKxC/DeXoNrIPQ7Wg6YAQ3eswaiizhUgjMtE7UX"
    "nzYUE8XQ6+A3MvAXgKy3w/XEZ6JyUES22LQYdTCFB5JNARDZ/UFi1ihoVIB0ts0QoomFvG94"
    "UfMA6gciwrMI+XAJiD57vBayKn8PeXlWTUTRrtjb9y1yImMbRnaEkI7Mi1DALmRoyrdxvLcv"
    "/sZYHi1HkxyM5s1OKOUY6YQR8hIbvBvim5H6PvNmhMSMkH4tYKZdfhw/Ad89rp/htXYGAAAA"
    "AElFTkSuQmCC")

#----------------------------------------------------------------------
_rt_underline = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAFdJ"
    "REFUOI1jZGRiZqAEMFGkmxoGsKAL/P/39z8yn5GJmRGbGE4XIEvC2NjEcBpAKhg1gIABS5cs"
    "/o9MYwOMuJIyetwzMGBGIV4DiAUEUyI2gJKwBjw3AgDOdhYrghF5ggAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
_rt_undo = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAPCAYAAADtc08vAAAABHNCSVQICAgIfAhkiAAAAhVJ"
    "REFUKJGNkstrE1EYxX8zmcSZZDJp2rSNfSg22CANYhYijWjAjcviwkVxW2hBVyZ/gZu6aOtK"
    "aLC7dicqwcdGiIrUoCIhpUVDsPZhq4GENqE2aUu5LuqkLxv94Fvce885995zPkmSLRxVffce"
    "ikQ6W123N7i41XOR65fPSeaeFH3wTAz390h7ib2D4+J9ZhGXajskWqxscq27C5MjP0nOEInF"
    "hQkIDgyJpeUCvjoVjyrjtCoAOK0KHlXGV6eSSGUZefxaACgu1cbH6W/0Do6LL/M5WjQNpyqz"
    "tb3NbKnClaCPwMlmpudzJFJZ/G4Hhm2b+OQMAApAp8fOykoRv9uBrlpYq+yQU6NRKbXn+ZFY"
    "XCzNLeN22Jj9UdoV0FU7umoHYK2yTmblF6nR6D5fAFobXRR/5tBVO07r+o6A06pgGM59QMOx"
    "9ddU4pMzhDu8ICtAHgAZwDhmrXZbYz3hDi/BgSFxUMBjkzA0jbXNMucDp3YEJJsVQ9cwdI1S"
    "uczCaoFsLl+N0ySHI/fF1eAZDF3j00KhGqOyWCgy8TZNa0sDXSeauNTuqw6KaWD37Zi4caGT"
    "ekPnXeYrp9uaePPnTKo1iSb5ZjjA8WY333N5JpKfeXm3f9dgSbYc2aHomHj6Ki2mMnPiUWJK"
    "hKJj4iBGrnV7yO/lrL+dfHGD4RcfSI70H4q25hdME0vlDZ7f6TtE/i8P/lW/AfYJsF99ZciZ"
    "AAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
_bp_btn1 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABHNCSVQICAgIfAhkiAAABLpJ"
    "REFUOI2NlVtsFFUYx39nzlx2Z7eX7S5FyrVcKrcW5WLLTVJAiZAGCQFjJEGixsTERHyQxER4"
    "wQf1RcODl8CLiRElJBARqGBUioi0GKDY0lIopaVAW3Zpt9vd2Z2d8WGgC3LRk3wvc+b8zne+"
    "//+cT/CfY7MfXyqCo5tgu0g7QVLvgx3W41aJR84Ym6txeQ1pPItRMArdrwKQTqSx4p1kU0eR"
    "7CT5acP/A5vvjyKb+gyzeF14eiVzq8oon1bEiJCOnYVrPRZnzvfRWN9MvO1Ph2TsK4L2FqI7"
    "Bh4NDmwpJ+vsN8sWlb60cRmvrgpQOgJsG1JpyDreb1YWznfC1wdiHNtXi3214TSKfJHkx10P"
    "gn3vjkXIusi8mvHbP1jM2kq4EYP2m5CwPKgiQCqgKBAwAAX2HIfduw6RbP75NIH00ruZy2Gw"
    "rPwmOG3ZMx9tX87quXChC/rikMmCpsL0sd4G0UFI2xBPwVAKykaDHZpC26VoidN7PUT25I85"
    "sP7OavLHbd20eT0bl6mcvQL9Q2BlQFdhaQWMCUOBCX9d9sBp25tPWlAShqvWaHrbGmcjZh3E"
    "PtmtAKCob46ZvYD1S31c6ILeAYgnQZNQXQ5Bn3eopg6b/gQMpnIxkISsDeUzQpilVQpCvAGg"
    "kr+tCE2fX7WwDJ8KrZ1eNqOL4Pmn79QSOHTKovaciqqCEDmBhOLVPpIHoUnTSF2pW+4UbDMV"
    "ZHaULHyicOqkApquQnMXSAEr5+Sg9S1p/rioUpQvKQh4303DE7E/AQNDXtb54QhqMDwGKzte"
    "VTWRb+SFEFLhTLuXzYYl4NdzLqyYqPPU5JyFHBdc13PK57Vwus0TWGo6MlCgq5lbERXVj2ao"
    "JNJwLQZjitw7Nc050dAeuEbDIxx06RsUDGUg7YJmaLhSF6rwGYOQZijjcispaG+DD/dm2Lpe"
    "G4bXNWU42eqQ5/cydVxwHM85R5pU+pMSBPgMG+HaGambMdVQ1BsZKz54Oz4UjBQFSMcE+89r"
    "+Pw279WogKBigsZ39S7H6sFQPfBd+QwNAkHQNRjojeO41o2EonbIdPTwkFa8aoUZGTlh4uQQ"
    "iQyYpqD5psJAwqZqkoJPE1TPEHTEBDFLEAwITL/A9INheJEXhJtt7fR3tx9IX3j7WwVASrnz"
    "aksbWdehJAJmAIpCgtpLKjuP24CLX4NX5oM/AIF7wgzAyDBgW0Q7LiJ1Y9fwzUsv3vC36I4v"
    "w/CPmzojjCbBlWD6BK23FAaTNhETjrS69CQVfD7QNNB0iOSDzweNvzfR19m5p79+0yf3SR9a"
    "snumKmXdvBULCudWlpDOQH8KbAfsrIvEwREKqiJwAU2BQr/3EJ34tZ1zvzVcVhy5qK9u7fX7"
    "PQWEl+6rlqrYO2txRWjh4nEU5ikMWZDM5J5MVQFTB58OvVGbY7+003yqqUPBrek5uqYxJ+u/"
    "xsjnfpjpKnxRPG7UwllzxvLklELCBTqa1z+wMi59UYvmltucbbhCtLvvgKbYb3X/tKbzXs7D"
    "W9O672VxIvgyKK+b+f45oaK8oBnw4bouicEksWi8PzWYOgF82XPwhf0PQzy65909QU1tqeOI"
    "MgcngiNdKd2bmm23XDu8sutx6/4BbTzYDeu8eUUAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
_bp_btn2 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABHNCSVQICAgIfAhkiAAABLxJ"
    "REFUOI2NlFtsVFUUhr99zj7nzKWdtjO9DBWkYGnLrS3XREIaMCZAguCFCCQGQV7wFkzQaHyQ"
    "QEKMDz54iRITA0ZjeBGJmCCJUoMiBEEQBCmUll7odWbaubTTOTPnbB8GC6gVVrKTneysb/1Z"
    "+19LcF+xU0Kvmb9PsmFX7l4ZYsKX4M4AyaEnUPpqpDUbXRYB4OTi5DKXEO5hCt1DxD5I3D/Y"
    "2r4Z4XlLlNdMe3DWHGbUVVJR5sNV0Nc/yrWWHm5e+QM12NKOm9lN5r399wDvlHjieyms2tq4"
    "ahVb19fQNBeKfOA4kHPAdmAgAccvwoGvr9LSfAQSNz5lrGjbnS3S7+Ka8/Zp4YYtm3ds4v0d"
    "YeZMgZ4odAxAVwT6h2E4Ba4DNZWwZFGIYX897e3R+Wq0owrn1KF/g61XXiY4442trz3D7s0+"
    "4im4MQAjGUiNwaRiUAoiCRjLwtAIKBfqqw2iZi2drZ0N2DUxnFOnb4O9L1ZCwYGH12/0vf1C"
    "Kb1R6IqC60JiFMIl8MhcmF4B/XG4GYGcC2kbcjl4oMLgWryceOuFhRgLviB7KqUBoIxNVtW8"
    "0ueenkpyBNr6YcyGSBI6ItATcVCuQuqwch5MLYdYElJpGB4BQ4OG+VMxpzSU4YpNAHmw7ltT"
    "t6iBuslwpTuvJJHOtyKZht87ND7/wcZxFLoGaxfDjMp84UQa4iNQGYTi6kaE5V0LICl5vQgj"
    "UDt7VpiBIfizO99yQ+ZVaxpIKTjXZSKPZ9mwzEDXBBuWgp2Dky1gynxOYUWYIV+gNmu+Gpb4"
    "9QIpAwWBgIdzbdATg+dXwszJt35Xu+1MxzVB5U2qCXh2GQzG4Xw7SAmG5UH3BwpIpkLSqwLC"
    "tTzCQaMzCpquWDAdTGPioRwvJSBUqIiNCEaz4AgNaXqEY5ia1P1yDOlmRu2sEbMlfUOCN7+0"
    "aaxSQF6ZJgSZnMJvwZrFJqbMF22+mGPfT4LkmI4CLDOLkG5G042kTBVejXtHG7tjw6m6YKWX"
    "aBp+vG5y7JpCiLwqpcBnwZ51jENPXMmx6xuBLXT8fjAMiPelQNndGcPXq3H2k6zQRXN3Zw9F"
    "ASgKQLAESkOCUFBQUiKYVC54Z6OgqS4P/bUtx57vBLpHpygAhYVQXAxjQz04SjTTuj2jAUhL"
    "7u9ra1GJVJopFeDzg78gf0wPNNXBkofyfT3fmePdZoH06gQC4CuA8hCobJpYR4uSutw/PnmZ"
    "3sM3zYq1VRlHNs6sD+OxwNXANMGywMGlqsjlesTl41OCnK7jtcAwoTQAHg9cOHGZWHfvZ/Hf"
    "tnx0166Q1etOpAaH1rjSW1o3s4RiPygdpAk2gpNdirN9GpqpY1ng80C4GLxeOPNLG21nL16x"
    "TbXR7jg4mjfnHRFafqhW19S3NYtnVzctr6I8ZJC2b+0E95YADXwmeEwYiGU5fuwGV09fanVc"
    "sTra/HjLbdf/I0pXfDUJ1/gwGA49Wb9wGrNqSygNWuO+trOKSCzD5ZYhLpxpJ9YXPYiWfSly"
    "9Kneuzw+kfnLVhxZoXRtm98nlwaChaX+Ai8AI6k0iVgyMjJq/ywc9g4eXXX0P4dnIvDfUf7Y"
    "9xUq51S7qDIADTEopN46cPjR/v/L+wte8dZC22ApeAAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
_bp_btn3 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABHNCSVQICAgIfAhkiAAAA/9J"
    "REFUOI21029MVXUcx/H37/y7594ul1tASKL8UTHTxD9zUxwYK3OK5sgVlG2WzuZKe+TaatNm"
    "60mbzc3+Th9UWipNzdkqjRqwGsGGdsNpjslVQLjA9R4E7p9zL5dzemCY6FVarc+j8+D3ee37"
    "O7994X+KGPtQK+prM9P00ril2EKRpIgpx0yhvMOx2btTNjfFXkKTdiMpHkmSbEXCTtqctfaK"
    "JQDK2DkNueSNF/Idj8x5gIuGxQV/XPvyZP+7g+suTeXY9NfGo9EdXo/YaauqEh8VTHnwxoT+"
    "bhZYfx2Rxs5GLHnX+0f7k0P9Jo/NcDB3pofKVblSRpZrG8/3HL+Jbox+UjhJ2pWXoylCFuRn"
    "g6ZAdx9W0mLPHb8CgJVnqjz3OT7bsWGyvrDYy4/t4POP0uQbxgjbtSja8PypaqXLrYlzvZB9"
    "P9g2dAYYSSTZzkdi7xglj4Mv7Tsfn7nV13BupCLLI+vLZjnoCUsMjGhEE9I0VVVnOZya6LgO"
    "GV5IJqGjl2jSZjMfiv0pH29cqtqLsPX6zSvTcyqWujjQLPjpPERNkCSYnAlmAgJBBmyL1Xws"
    "Gm8npFQuNdPacIsl+2sTbftOJaheYLOoAEbtG+hQBHqCdNsyZanQu088lpe7XZgZtSWPaiWb"
    "HhfUtsHJFohGacVBOXuEcbfqvWGAt2yFHo7PyWONqsFvfhqwWMU+Eb1XbWL4Bi7Rx5uAixhv"
    "87kwJ6r8DZeeKCMUrGQkKlBUGU2/itO9n6ZnU1/3mTo3MX0jsjwD1FEUFRTtO2qKfhgHO8sO"
    "DzxZmu2VVY2wKbjSNUTbReN33GlP0PDUtdtvIFp+rRPu9DLb4cHtknE6BIYRiyQPFrrhlpWO"
    "Dw6E8rILvdteXcTVsODMHwkOH2otPtPU4WPZ6dU0rPABsLypQG1pPJU3Pbso5MxD0RWmZIIR"
    "uE7QSA6NeTcXxM6uONLcGKjoHUhklS6exKisoWY8hGnLnr6A8RwPbz7N7FdUt5psmj8vNy+S"
    "lk9CkpnstejvCtHVOdyJ0Mpofe/6OJi+byNMq/7igs8ob+8M564ozULRVUJ2BnFb0weCQ+tl"
    "rC2LFhZkhhy5BE1BjidJz5Vr9Aci59Hkcg7mdt75eLdmbs2J4sU5a3e9Po+OaBoH6uCyP0Q8"
    "YSPcmeguyHQmCFy5xqAxUs9X+eW3E3Iql76jR/q0dbktrYPzV5Ski+lTdX5udzGYcOFNB49q"
    "0tMeZDic+JqaglWpiNQwwNVD3xjp661fzoZLl81zSUuLnXQZMBqN0OsPWrGY9QFHCl+8a3/C"
    "LG/ekP60z9z5vWFvOR62qb48QpV/+0S1f7Z5a8+t0XTHp6quqhFTbKUm/+C/n/Q/5k/sN4aU"
    "VfMVHQAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
_bp_btn4 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABHNCSVQICAgIfAhkiAAABG9J"
    "REFUOI2N03tM1XUYx/H373bO7xzgAAJGCOEN5CaCXEZpstlkZbY516i2bJUuHEvTudpaLWZt"
    "6VotyaVhzWbrolRbFy+ltnA6UQyVywTxriTXA5zOjfM7v0t/oISh4vPn9/s8r3337PMVuM+S"
    "ircfcwhCnm8ouJlE9zsc3qDfs/++1Kxamxqlb/xoU5nLriqPtv3lryDuCTfu/WfuNiLcXasS"
    "yUlOwNJsmKIqO6T6nd88ExeT5KL+SBe7vmrgQvO1FkSxkrOvHp0YLq2S6Ut4C8F60RGpxDlU"
    "WTJNC1WRHBVvLxPM6GgcdtBDBqeOXub4vkaz+2p3Haa4ko41l+8M526dTDh8OG32lIziRbNx"
    "PZCArChYgAiINic9AREskBVwOMHwh+hpaud0XUvoRo93u3Wmcs3tcGmVTN+klvR5uRnZi+fh"
    "CysMayCKN18gQBTgDoIogGWNnEt2iI+DYNs5/txVpw2fWGUHkEfh/rh3J01LzshevIBhXUSV"
    "YNgzgHfQCwJIokD89CRcThlMsKkg28DdOciRX0/T13ahG1lYf4v7DxbE50rKcslMFTFNqN/T"
    "RP1PxzRdN3sBUbbLiYVV5eL0xFjsCgz2B2g41EpTXbM/5PFto33d62O3OgpHudSkksIYZiTD"
    "pQsDnNzbYOq6sYTW1QfJqrUJkqczPVVJiI03+f3nNg78cEp3dw58j2pbS/u63v9nYBQOaqbx"
    "xQeHsNkky+fXhIBm9tK6+uBoo12Srp69zo597VZL/fUGnMpKOta2jkvVuFQU1pTi1SYT1g3s"
    "koLTfoXGihOj9wWfbRY1s9QM6ZvoWLP7buB4+F6VWZ0P0kZUuZ3Tq9aOnhdtTycYSiVs6gii"
    "jFMa4FRl48TwnI9j8LIlOT3+2UVPZcq1u1v8fr82lcaKfgDyt52LdqkzIyJslm5YwsBAIKCf"
    "fCUKxqZibKV+qaJ63rTbnetLl+ZELHs+H9OE775uNgmK5shqah5UQtpDK9Y/JuYVpXDj+hAf"
    "vvGLo/8mMR7OqX5ZFAPvzSrJSZr/5FxSpsXytw88Xf9ghLQI0I6TsyVMUEuZXTZHdSalcKkP"
    "Os4HGfQEPIyD82oeIWxscz2UlJu9sJCUzCkMmdDdPrIwp+Agb+lCUdetNMuycERHkjg9iaYr"
    "oDqhfm8rhqb/MQ62ycZv859+OCoiNw+PFzp7AGsENS2Y5FCISEvDGFkEpjnyvWMjLM7XnaGz"
    "paMf1fbaODgcFmsvHm9/Ya5TVtIyZmGpCgE/mAaYQKLTQlE0DNNCEMDULbx9blr2t9J87KIb"
    "m7KExoquW97tqciqzsKyPk+eOaWkZHGRmFOcgiiL+IfBHvTx4yd7CA5rmiiJ+IOG1d3r91lh"
    "/QA2VyVNLw2Npe4ct+zqMgxpa0bB1Bnly4vIL56Mt8fHiuXf+sMDwccxxH7sQJT9Go0VgTsa"
    "96xZ1auFnE/d5RuOWDsbuqzIBTt8FNTE38/oxD+voMaJP/R+TFzkKl/Y6NR90VmcLdcmGvsX"
    "ZajORhkOFtcAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
_book_red = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAApVJ"
    "REFUOI2Fk09IFHEUxz+/mdmdddddd7Usc/2LYoSWsbVqWIfoIEgQUd2yTt4ju3SocxBdO3Qq"
    "6BAEUVFRJCGBWaQZ/gs127RyXV1T193ZndmZ6dAallZfePAO733gve97gn9LrMvt/xWIyyBO"
    "VFAnUoRtD/vdW/yhlKbrnSOpjlcQBTIbAKkGDtp5ol0u8O8Tqjtkuz1+NT8PLAucKmQ1Hj8f"
    "fXps2r5gwPifEPlSqLRPKalsc+4NVcuW7cqW1mCU1GDuPoTZeBhFT1MrrdYE55Z89zXeAyuA"
    "9QtwPujoUgu8+VlDIGcSJMLtSEXbkPLyUUwDSXXB7AS7A44GZXrFeGEyCiTXIPJZR7q1uK5s"
    "Z+LjNK6S7SjRCHL0M+pAN1LfExh9C0YGyamIRp8jvPg1Nd9vMwmkAFtuMpnf5dBPu4PFIrGY"
    "wp2OI8fnwNBBkn/u2bLANHDlC6lJyraMzJtTkxABNKljmddjkwv3hJ0hvfAdPAGwLTBNMA3I"
    "apBcYnV8jpHeGIMle9ymEPVAFeBUAO1RlCvlQ1/aixurXEuRGH6vDrMLRKMmo4WlTFW0YJxp"
    "xRVuIVhepj2rq1YBDyApgHUxy3D9p+Sto+Wxzp5IkoXgTpaaT6HvDePz+/F5vRR6PLi9frbK"
    "dl5XMc6rMTTAUnJupO8sc620O3byRtvxQFnoALWVFRT5CgiILDVf37F17A0F/T1a//S3QWEC"
    "4AfUNYB9GyJHUlyvtNMXG1cmaO59SWB4wE5OzIzfjfPhoUF8wMLUbZaBmZyV9m+nvAd2nHPx"
    "QBdkbmpMDkFmBdJADPiSi1lgGUgAq+sBAA6gGmgF3Oua4sBqzvs0YJJ7rj8BACoQAKRcgwbo"
    "a6NuUr+pxF/gG/QDEGYH9mMazfQAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
_book_green = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAopJ"
    "REFUOI2Nk0tPEwEUhb+ZQgeYtrQ8lPAsTwkREgJUUKLooibEhSG60YWu/AWGhb/AjSvjxr0m"
    "bn0gC6MkoBgCATGCsVILyMOW8ui0006nM+NmICjxcVY3ufd+yc05V+DvEg7V1r8GBK4i0kUr"
    "CgGhkJ6KMrkrmdJV5UH2BmF+ANpRwGMuYDBY6fJ0+wRnZ6kkebwuJ5qaxZF1ocsZxp4vv9Tv"
    "M4xO6HeI49yt+rnGQv/5YEOt34jnS3WOVqrMNk5VBDldFSS+twXVieYNKeVmlg+AApgHgLJL"
    "8p36Go8Ujwukswku+i9TWlyOLLlI51LITplwcgHZX9ARs1SdBRaB1D7EobZrA4N9zY0Toe9U"
    "VBSxvLlKRA0xtjnCWGyU2d1ZNMNCdIpCfo0joOxpMSJ8BVTAcmjHjbjos661t5QLS5EMirzB"
    "lh5DswwEnJiI5EwLLZdDlC1Rr8n16StWmCgRIC3yhPF3b9dGJMtCM1K4hBJypoCBhSYYpEWN"
    "HXOPcHSXb/MJ2pKdRYicBOoBZx6gah9zd1+PR4IDA/X5b+aiOI5prMd22IlCtVJJt3mWM6X9"
    "9J3opbaqWm0abpIAGRDzAJNXzHyp23rU1Oy5ufF+mwZnC9e9/QRKevD5vbiL3bhcMt5iH6LX"
    "KCKAkynSgJlnu5ExFrj3bDQ8NLR8xdPX0UtjbQNutwfdoTGVmWB6c5KJ2Hh6Y3lv3g6gD5D2"
    "ARaThGjhYVbO3F7IfmJk6QUzqWkzsa2ECPOZJbaJomOgACu2ldavUfZTSw9PUVFYJMw6GhnS"
    "QAxYA1aBTWDXDlTyMAAgH2gC+oECe2ENiANJ2/sMYGA/1+8A7EWf3VOBNJA9OPU/JfwBfkQ/"
    "AU/kDpSM2ckCAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
_book_blue = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAn9J"
    "REFUOI2NkztMFGEQx3+77Hnc3e4dRwSJPETeBEwk8lIphEITqaAyxkQ7GitjLEyMrY2thZ2F"
    "DQUFCSpGEiNBjJHwChHlkRM45Y7Hcdw+WW7XwoMgxMe/msnM/DLzfTMCf5dwwHb/lSBAr8g1"
    "oQZVbMYnNyEHz2Fu67y6f5PEWAywjgJuL3cg2FdRvI14jQbwBRF9oBuImDiuBNNDLxnouQf2"
    "3GFIVlHXnYkChfZUcXGpP77uPSNbNAc1Oms9dNf5WU1axMivJLtcYWlwEkgBzh5AXNkyBU9u"
    "LvnrUcy0QHtdgJpShRyfRMKAsyUySBJUXrxBw4Me4CQg7XdA/pVLdkt9uXdhCS0QYjWmMhNL"
    "0zelMTyRZPLLBpgauGkBpaiZHc8am+PzgA64WXiqN0y57Hp2dbmgrCwQUSUSSQssC9wdSNuw"
    "u/vLd1wRX+l5jO1F1PkIYIhMPxxm9O2LuCNiih7C0g7YFti7YNlgpUG1Ia5DdIOGQsMvCOl6"
    "4DRwTAJ0vn54xLvKy8mOVk945D3YPkgYoKY4EUzQWqhxoT2Llio/RcUFesWz114gAIgS4PDj"
    "yRjTtc93K2puGYvjNOebtNVD4ymRUEhGCYWQAzLhHAXNV+CnsPsY0T4DcPZe0+T78GMG8ro7"
    "C/qDTTV1lFVWEVQCmK6fNxEfI5Eshj5rBt8Gp3AEAQgD3j2AS6x3jry2p7pw/O5MXGZgQeBT"
    "xHFSq2tzqB9nSY5uoi/YuHYKWAI0wP19lXMaSsjr6sdWU2wOLaLNWqQ1A1gDosAysApsZRZK"
    "PQgA8AAVQBuQnSmIAhuAmvl7E0iTOa7DADKF4UxMBwxgZ3/U/5TwB/gR/QQ8K/3nl/ZkqAAA"
    "AABJRU5ErkJggg==")


# ***************** Catalog starts here *******************

catalog = {}
index = []

#----------------------------------------------------------------------
book = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAhBJ"
    "REFUOI2lk89LVFEUxz8Td8yGnBmTsnSKfviIRGph7QZCIYNoIfQvuGoTtGoVtGrfxkULF0E7"
    "F0IFtol2FhqSbVQEbRYFI4SvUXz3nPNui+c8FKaVZ3nO/X7P55x7LxwzCgBTrxdG84yAIIgI"
    "b5+MLwFMvnw3KpLlRATZE0T2+DL9eKmQiQuLl/pKpKlhlpKakXhh6/efm957BvtOfycYqoqK"
    "oKr82PhFsXTqtgtpukjhBM8eXs8h0jRl/tsWqz+b86bKvVs1Hty5egR9dOoVXcXiogMwMwBW"
    "VlYwyzqNjYxw5Yy70NNT5mJ/L8vLy5gZrVaLer2O9wniu3AAqgpAFEWYGSJCo9GgsbnJ8PAw"
    "SVIiiiJEhDiOAfBJgj/ZhQsBVASAtbU10jRFRKhUKsRxTJIkeU1VabVaDAwM4L1HvMelpsiB"
    "QRRF2aJUaTabhBDymYeGhlBVdnZ2ssvyHhHBqSriPSEE1tfX8x2Uy+Vc3K61CWq1WmbgDxkc"
    "JvDes729TQghp2gTtHcgIqh4nEomAOju7s47lkolqtUq1WoV5xzFYvGIYXtUJ+LxScLdpzOI"
    "F0R8jjdZv0EIgTcfFrKOqtiB0MxQUZyIcHnwbMd3Pvv5KyrK/YmxjvW5ufe4/f19NuO/B52P"
    "EpzvP4eZMf/xU0eC1Cz7TJ3i2qMXM7u7rXFTpVzpXd2YfT7xv7PHin/ZG4/t2teD9QAAAABJ"
    "RU5ErkJggg==")
index.append('book')
catalog['book'] = book

#----------------------------------------------------------------------
clipboard = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAf5J"
    "REFUOI2tkUFLVFEYhp977h1znAnSCRKbEaGwNgZF0K4gV22iP9Am6Dc0ENU2cKFCtKtlq+gX"
    "ZLRqIS2MiNAkyKLSgZm8jV7vnPN9X4vJQRlrU9/ucM778HzvgX+c6E8Xs7Ozp8rl8lMzk2az"
    "ebVer6/9FeAfTE1z5Ph9xU02pBI3T14vlkZPuEKhQHN1UY68f7gz4r+JBVayfKs+enttASDp"
    "oSq1GVepnE2OllluXOHShct47wEYG7sWv8yT0rQ8Jmxn58PnjzPAuX0A0WgyGSnz6PUUb989"
    "59XiG0QEAOccjY0Gn05f5Eb1BZLb5G6uB7CgIJ7iUIm5ufl9e4pACHD3Th1qEUECfQA1hRAw"
    "U9rtwOrqNnGckKbrbG5+pVqtYgao4n+b7Qd0chCPqlEuJ4yPHyKKHHl+jCwbZnDw8K4rqgcB"
    "VByimBmtlrC0lDEwUKDdXidNvzAxUeuFvA/W34HsRISAiCGiOJdjJjinxDFEkQMMRFEV7Tfw"
    "HkQwM7LMk6bfKRQSvN+i0/lJp9PZVcVrL7+3xEDXIMK5IYaHS8SxI4SEYjGhVKp0SzRD9YBf"
    "IHQNyFvMz93qPt4zZlCrlLqWcpBBCCv5ZnrmZnUBahGo0qOo9s6tjQZm9qEPsJX+uBc0PFOx"
    "yEzAjKCKiBJECCKICEHDMlnnCf9rfgG9Rixh8s0DuQAAAABJRU5ErkJggg==")
index.append('clipboard')
catalog['clipboard'] = clipboard

#----------------------------------------------------------------------
code = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAw9J"
    "REFUOI1V001oXFUYxvH/OXPv3MxMnJlOk6atQR0XdmGtVNCYRYyg1YXgVkuL1HShC4VQW4La"
    "nR+LFqEoSoIbwRaKFEQkRYwupBG1kAoumqih1U4bms6Mkzsf9+vcc46LmqE+8Gx/vPDyCP7L"
    "S19ce0xIe+r+cm48UIZAGZQxBKnxhbUdK2gIhMbSAppI87nXaHzrbALWpGN7tg2OvzE5zJ3p"
    "JaYUJKbUivRooqATa/5qdDm/2t0XFivTfUCn6UgxKwCobWhcIXAEZBzwXMk9niQjJW4G9o7m"
    "2FkqVD795cYHsg8kqlg2EamBTiLwFbTbEX4EfgTNEG51NQBvnrnGeLXA7uHscB8YDDdGnvhq"
    "jvTlQ/QiTfXEDEOffUTg9+jEhm5kCRMwgNBtfr7SYulvf00C2MOHKzNLZ58tOCFKOASxReHg"
    "0mH73EmiVodebOgpAxbW2zGnFlbbOlGHZHzw4Ithu3Njxza3ZGpNakffJQUu7Z8mue6TFT0e"
    "ODqFt/gDUSowFrSrceK0+uXrjy5IHUZzydjuAXNpBY7N0B6sICToYoU/X3gNfv0dNfYgd8+e"
    "QCqFtZDGMS3V0wCSKHxFnl+MTHUn4vjb2Ft1JJas36A6+x7pfTsQ84vUpqYRWRelNd1eL/1u"
    "5uk2gMzPz5+dHZ0cu7K6gRr0qB6ZAgu73j9GpugQtAyXZ8/hT+wj50KzG5PGyTpC2NsXAPND"
    "u5IPJw7gxJCp10FIZKNO4MPV4ydRhRJYyDuSeitEJ8na5vecySNnhtI0euehPXvpTp/m++WE"
    "Qkfz0ydfM+BaXAeymdst5mG1FqCSeL0PRGH8lLT2uaXlq7RCh25sUdoSK0GSGlJtMNZSKZV4"
    "9Znt3GwG6FjV+4BRySPPP/lw7q0Dj/9vA9qC0pYkBSx8/M0aeRc63QCdJs07AHX1ZsPn9MIy"
    "5cEc5eIA5YJHqeBxVz6Ll5V4jmT/xAieA/V/OuhEXe8DJPG5CxdXRi9cXL5XCLEV2Ap2i0Vs"
    "wdpSzsu6AwMuxUKOcjHPbyu1P8iYHzeBfwEwiol55ANRRAAAAABJRU5ErkJggg==")
index.append('code')
catalog['code'] = code

#----------------------------------------------------------------------
core = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAmJJ"
    "REFUOI2lkk1LG1EYhZ+ZuQljPsSQkFAwbbMICKnQRXfRRegvEALG7uxPKbjJVuii9AdM3LpQ"
    "F+4rLUERi1QUP5MRgwmaxNzJzZ0urCGpiy569ud5z3k5huM4Pv8hAZBIJLi5uSEWiyGEYHNz"
    "k42NDbrdLq1Wi06ng+8/3TFQqk86naZcLmM4juMXCgXa7TZKKbTW9Ho9pJQopZBSorXG9w36"
    "CnzdQWuDqakparXaY4JkMkkymRyL5vs+vu9jGAbdbg+tGkSsn6C6DCJFhBBUKpVHwKju7u64"
    "vb1FKUWz2eTs7IzvP3Z59ybE21yKF6/yqHaXQMACwBw1NxoNTk9PkVLSbDa5vr7m5OSEr18+"
    "8+HjJ365rwlEsvT7cvyJAFJK9vb2sCyLer1OrVajXq9zfn6O1++j+pLd6jfeF/L4vo9pmuOA"
    "w8NDdnZ2ME2Ti4sLXNfl8vKS4+Nj2u02AGtraywvL2PbNpZljQOurq5wHId0Oo3ruriuS6PR"
    "wPO8x66mycPDA0ophBDPE8TjcY6Ojtjf38c0TbTWAASDQSYnJwmFQmQyGSYmJjAMYwgwAQaD"
    "AbOzsxSLRQC01gQCARKJBJlMhmw2SzQaZWFhgXA4PNzGMIFhGAghKJfLuK7L9vY28XicVCqF"
    "bdtorVlaWiIWi7G+vv58yk+RhRCsrKwwPz/PwcEBANFolHw+z9zcHNVqlcXFRQAqlQqlUiky"
    "NqRwOMzMzAy5XA4pJZ7nEQqFCAaD3N/fA9Bqtdja2qJUKtmAHAJs2+Zv2KienvbHbIxVWF1d"
    "rXue15+enn7JPzRqBvgN0r4cgCHFMd4AAAAASUVORK5CYII=")
index.append('core')
catalog['core'] = core

#----------------------------------------------------------------------
custom = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAvpJ"
    "REFUOI2lk19MlXUcxj+/933PezwvdF4OCBxg5g4cp9IQDHQsxWq6YsNlUW7pNKYXtLm5vGhz"
    "y7zLorpwja0CabU2HVt1YUuT/jAxU0eaOEUMEUqSIxzOOXA4vH/Ov7c7Jce66bl7novPvnv2"
    "fOF/Sjwa7Fu39HBFQeagLDs5yYxD3BbG6Kzr6Infw28vBpAXmtZa38GqUucd7TGhKm6BJAvA"
    "cQnSDQXeXOn2lHn2UYC00Kz1Z9s0TYhYPEN0LkPCgqykosiK8LlSBxa74F+AmbkMJU/vY+f+"
    "Qzz70l5C8woRS8FQ8tA8suej/Y3u/+ygc/fyyO4Pf8hP3uklYZhMR2fx5mrolVvoadser2vM"
    "b80YwW45t4r56T6w7rUoCwFmVhsy717ZkHYvxZeTxldYSiItQ3QYfZkaydU3d3sqGtADa5kZ"
    "W8lQT9cHD0us7XDdSSzZ9Hj4m+qamipQvQhJQXUsrvzURk1Ts+4rqxdzE7eQkwaat5jZyT8V"
    "ARBsPO2OEdvrofjjM531DHbsxMEBIN83T13jBvTy57FD3ZgRwdQfBknTjlh24ikZHJEKDOzS"
    "1WXHejrXc1VoXF6xg5HyHWRLSnihxkYPbsWa6ERSDaCI1Mi1SdOwnqt74/Sgsrr5i21lUvjz"
    "199s5lxEZtBwSFngv/8te4IX0YMvYt37BMmVJhkPMP7zb3x2Y9WnR491DABIxyvf//pES5TJ"
    "m99zaQKMmKDw71O87LtA0RNNJO93IasOdnw5ob7LFAWq2a73vfVgB5IQkuLWOH9pmqBi4Bvp"
    "5tWCi2SdUkLX28liMR8t4+4vtzhydRsuzYssS8pDwIoth8Z6v0wvSYbSJ4/3s97sonJjK+7x"
    "8wyf/JWBnij9Z65xoLeJPGfcGD33le2p3HzkAWDNa+3vafWb8v1+/FMziY6h21MkB78jUN1A"
    "Ts5KxvqHeffsM7G/UkU/qi41oD1ZV7impf3woksEeGVjnllbUaysW12O47Iv2OHwnq1t10cX"
    "+wOAfwAJ9yQGhieeeAAAAABJRU5ErkJggg==")
index.append('custom')
catalog['custom'] = custom

#----------------------------------------------------------------------
deleteperspective = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAnpJ"
    "REFUOI2Fk0tIVVEUhr+9z9nnmrc0095RVIJSCNFAGkiEFDXIRk6aNCkIoiALIiKiJpZBEyuK"
    "GkQIEUhCCGVQg8pKJJWil/nonXY1vd6Hj3PuOatB96aV1IIN/2Ctf63//9mqufXlYF7OzJAv"
    "QqYCgYkxF8/zGBiKat8NhqOx0S27dmx+wZ/1tKNrLAgCmfp835fkmCexuCcdz3ulq6dPmu62"
    "D1yuu73hz3n9FyOglEJrUDpAW5oFCwvYUFZSUFS47M61Gw8q/0sggAIcx+bd+0+0tLTT9uwV"
    "fmrcScSi9UePn6v6JwGA0gqtYG7BHNxA8a1/hO6eTzhZDvHESHWmz552GNBKkfJSlKwpxh33"
    "GIxPMNTXhzEOrS3N00gIfHjdCp1tBEBKIGUMid5e9OkDmHsNmOwwjmOw9OTeSfT5LTxpgmQU"
    "+dhLsqwS+dBJXu0RQveamLH0Md7qUvS8xSjFNAQLV8KyIrjbgNV5hfDTR+jubszD+3iLVjC8"
    "9wRWwXyMCtIiMwRpPK5t1PpK1OgE5vpFQi8bITKMt2oNQ8fO4y0vxkoksGwbNeUEO2NCygdl"
    "LGydhfoSga8DEB+HL99RgUI5BkuBpTJBp00MMs57Lk7dWUI1h2FgBH/tOoJwPqbtDflbNxG6"
    "1QgzstPbJy/4lYLd3IQ5fwr6B3G37yR+9Q7JM5eQnFysSITZB/ehI/2IcX6LfFJCaTmqfBuy"
    "pBB3VxUigldRQbT+JtmH9pPcvYdgVi6Wl/pNgh2kcTgvB05eQAAD+D6IgL9xPW5HO8oTwkkX"
    "2zZMzdEeiceT1TW1Ka0NP+3xUViI+IiApH+GiIAISmmSsdhEhuAH7okWfiVuCWIAAAAASUVO"
    "RK5CYII=")
index.append('deleteperspective')
catalog['deleteperspective'] = deleteperspective

#----------------------------------------------------------------------
demo = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAuZJ"
    "REFUOI2lk0tPYwUARs9te7l9pDCEPmCGkQ6FlostwlCKCk5MGFw4asDEmBg2Jv4B1vMDZONa"
    "F5MMW6LRhWhmYWYzwvAsj2mTYkcqhZa+L7X0cft0OwsXk8xZf/lW58AbIrzGRj8+Pj7o8/ne"
    "uXdv9r1cTiktLy8/BFr/e9Df339rampq1O/3TU1M3PUNDDi8JpN5QK21xVpNZVR2IsuyNxwO"
    "BwF0w8PDg/Pz83Ozs9N+r8czYbX2DjXbuq5kpsJ1IUkicUmpkiRfMpFIpOjr7WFhYeHByspK"
    "EEBYW1v748Enn86tP9kjGM4QT6kIooXJt0184Ldhtd1C1GmoVss82z7DeqNJp6m25fe/PwO0"
    "NKenL5PxeJKH3z5l9ccoh+EGoqjHK1uotuycXTaIXqhkFJBdb3GZLjEyIk86nU4ZQGswGPuW"
    "vvri493DS7JKg2arib27jMncSyzZJpnKUShWySkq2ZxCJltk6I5F+28h98/m5vNNbbVaFZeW"
    "vvw6kSoLhyGFZqOGpC1wXdaRzLbpNOupVK5JJBVSqSy/PjlC39Fi7sMx06NHjx9rYrHYyelp"
    "9HJs1I5eMnL7tpNqy06v1cBNmw67xcC4dxDZ1YcoXFMsi+wcxHG7R3wul8utAXJ7+8ehYYeV"
    "HkeRtlik54aHeK4TS7eRmzYd3eYajUqCZiXCRzMi05P9mExdHYuLi59rAAKBwF63WUQed3I1"
    "s0He8RtdRg3FUoXIyzP29wOYjS3enb5L5vwZumaUi4sLJZ1OCwKAx+NZ+PmntV9enGj50/w7"
    "Y2YH7roHq02i0yyh0YCiKI1A4Ci6urr6dyQSuV+v15/GYrHPBABJkobW19ePBwfvGCSMIDTI"
    "FFKcnPx1vrsbeLGzs/M8FApt5/P5IJCRJOkbvV7/faFQ+E4HoKpqbGNj4+DqShnZ2to+Ojg4"
    "2A4Gg1vpdPoYOAcar+ququoP9Xq9QxAEy6stuIEOIAJUXzPGN+c/irhDxtglzjIAAAAASUVO"
    "RK5CYII=")
index.append('demo')
catalog['demo'] = demo

#----------------------------------------------------------------------
dialog = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAJ5J"
    "REFUOI2tk1EOgjAQRN8ULkXizSrRkHoySHus9cMULQJa8f1sMtmdTnZTyTUcQWEI9utwf72o"
    "BfC9R7p9PWjmkYRcgwOqhpf9bXasRToDPBJk0pSqKgBhCGZmFsdYVQGTa54GtSZvBn9J8Aow"
    "N6/p2WBe4tqCulO3qRdnzKKk4lRpSpt6pkhgZsQxzjUnWNOLBMsXatDR3+g+t+xzB+jeEF9n"
    "B4s2AAAAAElFTkSuQmCC")
index.append('dialog')
catalog['dialog'] = dialog

#----------------------------------------------------------------------
exit = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAthJ"
    "REFUOI2lk91vU3UYxz/nre26ttkGpZvdWJ0LkF3AhWSijMQoaEKMLwn/gqIJAYyaQLwwxmAm"
    "S9BLLzSazBhRYBqXErKEYTJggwwYvgADRgPr1rOenb31nLZn53d+XhibSORGv5dP8nzyPM/3"
    "+cL/lPJw4SvYpGvKgUQm80p9e/vawPdZyOXswsxstuyLTw/Br48EfA17W7ufPLZx//5o83PP"
    "YxUKBHMWSemTPzfM2KkB/8btqfeBYx+CD6D93dwPezftefXzp7/9zmjY9gylhUUmxy5j2zb1"
    "5QrpJzrZ0Namera1617BdEbgfG2Cfuhq7t46/uzgYERPprAnJijncshkEgm4AwPUS0k8kESX"
    "bL45fVpcnzW7P4Mr6l+LKPu63nk7oidT3Dl5ktz4OPlLl1B8H9XzKObzWFu2cGfqLsK02P5Y"
    "WtNV5TCAChBPp15LeUUWhs8QqBqdO3dCfhpWV1GEQE5Pk+npofH1N5j67Tp6UKEhFtsFoANE"
    "081rguwJCvdWaP5xCOvE96TXJNEjEdA0WkoO5ie9tB7t42JDE9EHU8RDRqwGCAJJtVRGiYSQ"
    "noe4PIoqA6o3bgES6S5TGR1FlF1CmQzVyd8RkSg1wKK9uFB9fP06LV9Ea2zAt2zun8kihn7C"
    "XwVn3qFp+w70WAJpmkhFZanqubUbFPNm1lJj6PNzeCMXSB3pxUilqcw6uJZDfdNaOvr6qN78"
    "A3fiCm5dmJlK9ZeajUdhc3vXhvGeznV6aXKGllNZRDyKM/AzUggSL7+EEQpxbfduqrnbjKEG"
    "V1ecHcfhggYwBObm4rwr400vtCR0lr/4EsOoo27bU4TbWqmcO8vdt96kcj/HLd3g4nLpyHHo"
    "/8crfwC6B+92dLR/vDEWUhJzFroICHzBilOmaBjcVFSuldzeEnw0CO6/hukgbDXC4fcaw6EX"
    "w4qMCSFYEtI1V73hJT/o+wFGHp3N/6A/AcbQQIv/cYpDAAAAAElFTkSuQmCC")
index.append('exit')
catalog['exit'] = exit

#----------------------------------------------------------------------
expansion = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAlhJ"
    "REFUOI2VkjtrXVcQhb/9uPdcS4okSyCQwSkCEqRwogRsFzaCgGzsVk4d0qQQpE+RPj8ivZpA"
    "qrhKcws3TiOnMNgqLGxDGgkhoat7HnvvmUlxpCiPKl+zGZhZzJq13a0f3v66fL36IicjTQup"
    "FlIjpLqQGyG1hdwKqRZynSmdol3BSoO178dxZWVu87P1pXh6CudnMJ3C5AymZ31tHrKAeEgK"
    "mujxgD7djMuVy2tzVBMHeQ7OJ9AuQNNC20BTX7wNNFNIHaiBx9j/Pea4tmx8/QkcHR3z4sUe"
    "W48eAGAAAXBgBppBiiIqaDGqAXz1vScGYOBh4ARJNdWAK45fQn0MzmErn6OjGUoxNBpVgIE3"
    "IloAUDNCiPyd9udvkFe/QYD47TPs5j2kGKqGB4oYUbRvrqqKg4MDdnd36bqOjdv32Vhcpput"
    "wAeMQBEwVUQUdaCmRMwAyDmzurrK1tYWZsa1mVnK6xmYWQAfEAKmhogiYhQMFSPahYCZMRwO"
    "WVxcvKihfPlTn1YB7RKlqVHtLRQMMyOqGv/GDEpWZOgxIPs+Oi2GmKKqeLsQQPWvQeeuBGzg"
    "sV924N1zQgjIwx+RpVtoN0XE8GqYcXUDgMnknMPDQ1LKVAtLfHC0j/3xEh8C1k5Q9Yj0FtQb"
    "mBEv5+fn56lGI8bjMV2XWP/0Lrd9pmQBFUQFUVC1fgP6zWPo/xyj0Ygn29v/uEV2O7iPHmM4"
    "qusfEqiRIKiHYTRicLg73+2dfHxjMNfVmZIKpU2UnCidIDYiF0dOCW1PQAuXhoN37L85Pf9P"
    "Av+XPwHwQHwFXrN+IwAAAABJRU5ErkJggg==")
index.append('expansion')
catalog['expansion'] = expansion

#----------------------------------------------------------------------
find = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAtRJ"
    "REFUOI1tk8FvFFUcxz/vzcyb2e7utMx2d1tbLCutuCExHDCKJCpRSDAGDkQPhGjiDbjoCf0P"
    "9AInOTZKjCHhwkVJwNgQMcRYisJa6oaWggI17K7d7my309mZ56F2s2v4Jr/k977J75Nv3u89"
    "wX+amiqllOfdzGcSo3Gsg00/0hCsI6o13y7Pl88cP/rWpzxNF6/dSd9ZqC7Fcay7qx3HutKI"
    "9Uy5pmfKFT154dqZ7jnZfYi7eq01WmskoKwNb8izeXv/yx+d//bGWbQWAGY3wDQFa80W09Nl"
    "gvUQp89maGgLQ1tHSKccZu8+IgKk6jt+6rOv3c/hWAdQmatS9ltcXlgkU9jGeGGUhCl4XG2w"
    "9PcsYxPjZAezzC8+QmMihXwHeK4DuHLlUi4/OuzsOHCQ4hsFMhYowBnL82D2L+7fXSCZyeOm"
    "k5gqga0sAcgOIAzWPgzcQn9qrEDtHwgToCSsaVhJDdN+WGNYrZBKpTGVjaksDegOIIqjFyst"
    "l8oSWAH4yY1bbaxBzZckwiRjJjiOwlI2liF7t9D0V6t2vILXB/0KPBvSCmwNoi3QgY8UEsdW"
    "JBwL0xC9gJV6/Zv6/C9tGS6zYxwmRqC4FZ4vQNZ4QiKqk/SyGKaJIUHI/yV4/b3914vbs9Uf"
    "zk3y+89zCL+F8Fs8vP0H965fpemHcP8SYn0ZwwKxufpNwOFDhxlMmizeLvH9xcvcnHJxEg7e"
    "QD8j+QxPpr8knatiBFeJdp1GmE4voFKt4Nk5Dhzcy2tvvkKt3kRriTuQYrWxzMyvJ9miMjgT"
    "Fo3ZU4TNlzQQ9TzlzViOMngm6zKSS5FUMJgZYOeJ7/jtp2XCuRu4xT5elZPOqEuuk6A/9PTc"
    "vT+bt0q34hgZaCCKQeuNEpbLUvYTSuc+Nt7Xsdqz+1lnT9E70gHs25f33/3gxN4LX50doPdf"
    "dckOt6WjXLvy4xfrLxzbVVrd2fgXbJkZTtWGQBcAAAAASUVORK5CYII=")
index.append('find')
catalog['find'] = find

#----------------------------------------------------------------------
findnext = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAuVJ"
    "REFUOI1tk0tsG1UUhr8Ze8bjPDzOuH6QOA/nUccqoBaBRNoKqPqQyiJdIFghENkgyooFahft"
    "nlXEAthUiqCLqhIbxAKkFIgMilIgpdC6YCoaKlBFq9iJXY89M57HZdHYiqX+0pGO7uLTf85/"
    "j8SOVlZKA6phXE8notkgEE7n3RcwdGFR9z1P/NOfuDp3/v2D7JLcaepKSDIGI4OTw7o2nY3r"
    "nZoZjeue4xA9cEAax567eubctccCAIJdvRACIQQy4DWbCM9DHRtj2LOeWXvr7T8QQgII7waE"
    "wxJ202J9/TZO20Xri5DJDBG2LALbxjNN1KkpktWfZr88+vKdeZjsAirlKrdNi+WNuyRyE0zn"
    "skTDEv9VG2TqdXzbpl2tAqDm80w+eJD7NpO51wVcufJ1Kp19QsufOEnhpRwJBVRAG0/TrtUI"
    "HAe/0UBSFCQgsCzavl/uAlzHXnBiOX1gPMfWNrhRUGWwBWg7DnbmZLtY5C8RcRc2N9/pAvzA"
    "f7pixajcB8UBs//RVhs25Gs1PNNEUhS2i0WaE7NsHJ5vNb5f9rspNM1WNRI8xOgDXQUjAoMq"
    "RAS4rRbCttleXcWeeZLRDy8QDkm9MT6s1y/V7/zsyW6N/DTMjEBhFPbmwBeCytoa5t6nSH/w"
    "ESEZJFnuBbz42vG1wlSy+t3FJW79WEYyLSTT4t7NP7F9nw19hOTCMaR2jZACUif6DuDU/Cn2"
    "9Ie5e7PEN18sc30lhhbVMOI62uJlNtc/5fDWEiGniL9/ESms9QIq1QpGJMWJk4d44ejzbNWb"
    "CCETiw/QatT45dd3GVITaDMKjd/P4DafE4Df85U7tjQ1xHAyxkhqgH4V9iTi7Dv9Fb+t1nDL"
    "14gV+jgoL2nZGKmuA901RPnvf5s3SjeCANkRgB+AEI9KUmLcT56ldPG90BsiUOeeHdPmCsYr"
    "XcCRI2nz1TdPH/r8s0/i9N7VLkXciUE/5VV++Lg9+/r+Umtf438yITEwJvx/5AAAAABJRU5E"
    "rkJggg==")
index.append('findnext')
catalog['findnext'] = findnext

#----------------------------------------------------------------------
frame = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAHhJ"
    "REFUOI3tkzEKhEAUQ1/+zK1dUWT2ZC56rG8xiIKg+7U1TZokpEgkSzyBylD8rrntO2WApm2Q"
    "vpcG96qrLGQJA/4y73V7fV6To5A+ALXBivk3hxiAMhR3d5/GKcSAy9IWEA05BLwN7jfIdRQK"
    "D2kb1MM32rXkHAss9IUYpp5t/QAAAABJRU5ErkJggg==")
index.append('frame')
catalog['frame'] = frame

#----------------------------------------------------------------------
images = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAylJ"
    "REFUOI1lk11oWwUAhb/7k581XfqXNF1tunbVLVVr7ag4ZVrrNsaQbiJaZKBDmRWLoi8b+jSK"
    "MPVBQV8UXwT1xfmDLXMZVijinNrJOqzdZtquadIuTdI2aXZzf3Jv7vVBmJqdx4/DgQPnCFQo"
    "ej5+PNzkOyYJwk3mAKYlUCgaxGLXxhIz4y+MjIzYAHJlgOz1+TvbGgJCBb9hQCKl0HV35HmP"
    "16XCyCsAYmUASz/rzi0QRBFEUaCxzsPeh3e+/Pno5FsA0n9Np57CLWZmBr1uqzf96xfk539j"
    "I3kV16ZqqmoD6JaLpVQGQ9fRTXZ3Pzjwb9HRAQarG+uHN3f19y4S8SFWs6PFhZ25Qj4Vpyrc"
    "Q/jxEyzlbObnFlE0i3Q2YwoApw9xsnXvwBudh9/morqN937yUJag20zy7D6Vufg0N858jGD7"
    "2HH0U5azKiWjxJXY/IY0OsBQ/faOd5xNNd+rid8zq+Wq8JtnAly6DG1alKmmT5iouobZ2kEk"
    "Nsvs1RkCXQdwy5BdyxvS0L7gV3Wd93gvfnZ2KPHHdHxX35ZDnSGDbmeS1x7NcTL1JRPajwTT"
    "RV7t3c/k6VOE7h/E568nlU4bsi8UaLnrycdkX430tSg40paQyDMtv0BEB1Pg3dUI55d9HLSa"
    "cDfEqHVraNk4weatuEQJeenPhfHgufED7fdtDyCUYGURNAVKGhgaexydPQtNlL0PUfgrCsUN"
    "cGzcbgFREpDzBf3IxAffHvTfVnO0py+ya1tH3T8mQwW9SNkqsh69TmAxQVZMkt5p097YjAgI"
    "goA0Noc6tsBUv9/45vL0cri5Qe6q8QOKArqOYOkoSoHVdI5Mi0Wi9XbufeJ1JFEmnrxu3Fzi"
    "8DlyhsLweDR2yczlwNZAKyIUVEI9Zba+WGY+CO19Q3h9XsAGxP8v8YcUxgN3BNs21tXdm0s5"
    "3JaGpFnkCw7fTcFaaz+PvPQ+luUgCiLx5Ipxy5nufO4js71e58LZD3HSs7iwWTO91O0/zNNH"
    "TiB6PGiqjccl4pIkT+XpiF5IHy/p68dKSgFFUSiXQZJdVNcGKZsGhq5jOw6SKLG8ki38DbMJ"
    "XHT2R43dAAAAAElFTkSuQmCC")
index.append('images')
catalog['images'] = images

#----------------------------------------------------------------------
inspect = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAp9J"
    "REFUOI3Fk+tLk1Ecx79ne+Yed2tuc8vlLTJF1HlJcoqaaEZaJHQjsIJAqBdlQr0JohDqVVGZ"
    "78JukHTRl0mYUEpleWFD0OVyCtN5mc+e5Ww3t7WnN3tirD+gL/zg/M7ly+d3fucA/1skcYLj"
    "uLIHd9/0OFbspZFIFKyLASUSWy623y4pLyfhxP3C+KS6+lCK/xdZqKkzqNUpYq/danWbJ8xs"
    "Tr5h5/vBlzeNlU29ZvOIO/4MFZ8U5le47bYp5+nWZkW6Ji0SmKZnRZodrom3H5ZzG/YUOZnF"
    "uURqnoB0XLp3/OvwO+OJA61MyA025IsE7JbVFXbZ48lS5vnMpuFwzeEjGYaiKurb2OAIAC6e"
    "gJJK5V0bqy7vjwFmxiZkQ5BEWUoe2fQEWY+YStaVZ9ZzTsdi3ja15jKAWwC2AEAQMxBvBX1p"
    "almalxAq/DsS3WCdLtvo5JfPNmba5AttzhFQDLu25iksqJADSOJL4A2ENC3r9wR/0kKBICIg"
    "glASJfJxhLBBzrtOU8kbhGDLUFIi02/PHI+/O37APe7p7JZSyl6Xb02ilab75GK10qhv0AHR"
    "CEegHF0Y2jVw/VmqsbL+Al9/PEF41bXEtJxqm31lerh33edQyZLkegWdUqQQq4q/r0/uO3Oj"
    "pdZinZ8am/xoA/D3PfAtEQJIBZB5paPrqnXaXG8ZH3fQAklArlPI+ode5LgtT+cNKlKQcfT+"
    "boeDsfMm8T2VANDFAgcbT5bptFKtP+R39fW9NgEQtjdnn23eX9s266GzOjofLSJBAgBSABkA"
    "DAAqAFQBMAIoBZANQHbtWE73nfO13NLMp6ZEAnAcRwghIgB0LIQAogCCAAIxbK61SvNEn5V7"
    "Tq9Vdf3zmRKIeEUTFxuLNc89/nDdH/xlAzHUigZXAAAAAElFTkSuQmCC")
index.append('inspect')
catalog['inspect'] = inspect

#----------------------------------------------------------------------
layout = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAZ1J"
    "REFUOI2lkrFrFEEYxX+zHBE0G9BCRBCVJIqdoI0YK5FUgkXSaor8AynSWQhWtqkEtbHTRiwO"
    "q5QprzHgoSSQFBaKJIGA2b2Z73sWu7e3ASMJPphi2J03v/fmg/9UAHi80lsKcJkQZoBbyAUh"
    "4CLLAlkAd8eS9sY6bFy/NHEbF8tzNwIAT1Z6r3RCvXj/RQAdAAXuAbxZ22nQ9A/sxbvn6G/v"
    "lY0BxoXhx+nzp6ps4e+Hv/4oASiKwdiIQDo9vPXbz/JY5ck9jAjcO0O048rNaRFUrzH/bJXC"
    "HRd0nz/g4etZ8jzH3ZtlZnxY6CK3loFXbr8OIvdvXqTb+w5Ano8zNXmFOiaS83m9X+1TZZBV"
    "BlXn+4URJX6XCQAzJ3C4zWRWp04jglATlGXkIBpWxPonRxIgkJCE1TcrDVoRWq+u1gCkZLis"
    "ieAS5sN9i8CjiXqsP61tNQb5+Bk2NreJMTKIEUtGFjLq3kaTaO5bwNX1l48O5X07946jJNdu"
    "Y4Dp4/zT1WuO7gTXWfcEcuSGPIEMNX24QPsKWf9I95PoDxEAIhVEfbTGAAAAAElFTkSuQmCC")
index.append('layout')
catalog['layout'] = layout

#----------------------------------------------------------------------
miscellaneous = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAklJ"
    "REFUOI21kklIVXEUxn//+67ac0LNCQcUSpMCUxdRhhLWQl0k4qoBMV0kiGATEVSrCNq1iEAN"
    "sxZtkiipwLICtQg0DC2TJIee+nJKvW9S37vvtEglrKCIPjir7/w45/Ad+N/Sq+y7NpX3nf17"
    "skKSa14tSYNDpNEpEn6459Yfs1FlNyoPDIkcGRY5ulrloyJRlbaOnzb85dpmoN4eBOEfwPAB"
    "AmmRkH8lKe9+024rvPas9Wo/glLCPsfp1BHd5/digJEIOTrszYDEBHjwBbjbm/fTRCkk3Gwo"
    "dcrwU5GhJ9J86qSflyJ0iWR2i1i6RFSnCC9E6uWa6NeT69ZYy3JVRIul9tJtFZEQyOwEzNrI"
    "Sg1SMy2f6E7OJkZgygC8kHKvk4yCj+TszCh8mzKW7H1otCp3dewj654dxQwMgx4KpsDiPMTF"
    "c6gt39N37qrV3j5IVvUJrFoISgO/8jNp2um/3HdGc7lNmFmE2BiwfQanE4qOQVYh6dONb/Tw"
    "4tH5mmzs5iSP3z+nbbADp25QEJWPZUHF6Y5lIXrO9f2g9AyQEOjvhrkxPB5BaSvLzAQwyAi5"
    "aTk4zRWcC8vU25vB60Ovffb1YuvmsGLN6wUPMDcBIqAUbpepjQ7Zeom0bENpjLvmsLntiPhB"
    "QYDPjwJICmLrQFnCUFiAArvBtFdjf4dx550pxwGntS725tJ2VZEYFse4YwqlFJYew+Zrchet"
    "RxkK0YOlqVISrHUC8RujDjwYfH5LY64EX4h2E0jRRn891t8Zq8rc+Hz/rG+GvgB5gkbPfgAA"
    "AABJRU5ErkJggg==")
index.append('miscellaneous')
catalog['miscellaneous'] = miscellaneous

#----------------------------------------------------------------------
modifiedexists = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAAkAAAAOCAYAAAD9lDaoAAAABHNCSVQICAgIfAhkiAAAAWFJ"
    "REFUKJFlkEsrhGEYhq/3fT9jxviM6TOnnEJW4gcgKX6AJhuUhYWyIAt7+Q0KS0OWsrWxUVYk"
    "hySNxkyGkZzGZ2GQxwKD3PWsnqvuuwulDd9X4pRKsDssxLRMzExK8ae0AWB4dkQC8QjnJseZ"
    "m0FtvtC+08rc/ILSALUNNdI82EJ51KaypAK7MQD1huWVZQA0gCjhxJxxzCm3T3dkuODxIk+8"
    "Lw6ABeAv85PMJnEbCpg3yOPyvH1FYmlfFSFtNLn3a96zcBvL4+yW464+8h0N4PP7MPcK77VF"
    "KB3ASdlE7PBfyAk6GFfxVnjFysLNRo7B/oEiVFQQ6olKsCOMu/dA6DLAwc6h+qG+hI1OjwlN"
    "ljhtYfktWGnzWWc6vOKZchhaH8W7VYfV7hN+RQP0dvaQTCVJPWXwpBU1kWompsblz6ZoS0y8"
    "iRj3lS72kQdrsUB67fT/Jl9VmVBnxOmK/tv0AbSrcOMtNiLbAAAAAElFTkSuQmCC")
index.append('modifiedexists')
catalog['modifiedexists'] = modifiedexists

#----------------------------------------------------------------------
morecontrols = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAp1J"
    "REFUOI2F0jFLG2Ecx/HvPXeJUROiPUmgmA4FqUUdpBTEaNFJHaSLxfQVuPQNFNpRhAwuvoAu"
    "Qk86OJQSBUVXaUkrImjFOKjxSkIaNNE8591zHWyN6eJvffh/+D/P89Msy/K5Jz+/fkVkMvia"
    "hhof58nz57dnBkBHRweFQoH29nYMw2BlZYVMJsPl5SXlcpmA4/D53TvwPCbn5ijMz5NIJEin"
    "02iWZfmjo6NUKhVc10UpRa1WQ0qJ67pIKclubjKq6/iuy5py6RkYpK2tjXw+f7NBLBYjFos1"
    "rF2pVAAQQlDOHeH/+I7vXtP3LMSLkRF0XSeXy90Ad3N+fk6pVOLL4CAPe3vxpMTzfUgkENfX"
    "eJ9KbHx8iVKK82y2ESgWi+TzeZqamojF4/R2dSGkhFqNy1IJ3/N4Gm3H9X1c36cajdYBKSXb"
    "29vous7Z2Rkr+/usHR3hui5etcqb/n5wHD58+0YgEkHXNH79/l0H9vb22NraQgjB8fExlYkJ"
    "9k5OODw8xK9Webu/D75P9/v3vJqZIRwOs7y8XAdOT0+xLItEIoFt29i2TbFYxHEcOoAH/f1o"
    "SuFcXWEYBkKIeg8ATNPk4OCAnZ0dhBAopQAIBoO0GAbbuRxC19GEQNO0RsDzPPr6+piammJx"
    "cRGlFIFAgGg0immadD1+zMdwmPGxMV5PTiKlpLm5uQ5omoZhGKTTaWzbZn19HdM0icfjhEIh"
    "CqUSA8kkKhxmbWOj4duNf2VRSmEYBrOzswwPD7O7uwtAJBIhmUwyNDRENptlenoagKWlJVKp"
    "VLihB62trXR3d9PT04OUEsdxaGlpIRgMcnFxAUC5XGZ1dZVUKhUC5C0QCoX4H7ubf4/2d1hr"
    "uMLCwsKZ4zjXnZ2dj7gnd4cB/gA1hCWaJRLM3gAAAABJRU5ErkJggg==")
index.append('morecontrols')
catalog['morecontrols'] = morecontrols

#----------------------------------------------------------------------
moredialog = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAaJJ"
    "REFUOI3VksFLG1EQxn8vu4poK1KtYFhCscaDpVpKLyu59D9oi+A/UDS5e4uKSDx59yJaj3rw"
    "Li20h4Tdg5deSpMSQnJoS1vUGoiaxed4cdeNrujV7zK8mfd9880wBneA8dJ425t+uNX5uiPT"
    "rJ/+kd9S9Gsqt5iT2wRKP0uMvn+GFs339RLJ+DAAs/OzygTIzmVRaulGgY5+TXLKQ4tma1tz"
    "/DeLUgoAE7iB7PkmwdAc6X9o0ShDo9SC/6nLBBDJXqM/WbV4Zb0gpoR2ATHbENG8WftPgwLV"
    "2hDls9ovM0xyCy52ysYtuDzt7Wc8OQgxj1Ma7B3tI6J5PtyDp4WRxCN2vnndZhTZTtnsTpep"
    "fj3k5PiEZqzJxGQC4YzVDy59D/qoVCpgsk9uMSc+nLwTGWeWZiRd7pJ0uVNWNlfEyTsCSLDE"
    "KAfhGE/Eae8ZAwXFH0Uyk5nLucMOwgACB8sby/LusyUTXyzhMS0OAoGrtoHgXW/U5aP7SaoH"
    "NRmwBoJ6ywh2yg6O4+pYUXkfsXBSRHDyThD9HUTlfVxcYmuH+4VzlkEmgUrj7QoAAAAASUVO"
    "RK5CYII=")
index.append('moredialog')
catalog['moredialog'] = moredialog

#----------------------------------------------------------------------
overview = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAkVJ"
    "REFUOI19kUlMU1EUhr/7+mj7Sm1BSgsU4hCDgQ0JjhCTJiQu3NVEo7KRVdW4dOfClSv2sjBd"
    "uHGjiUMwURwaIhICCBEhQashDGppqbQQOtE3uKCQloJ/cnPucP7/nP9cQQGhUCin63qePSCE"
    "MEWj0Ynu7u5LwHJZgt1uv6iqqrHfymQyRjgcNoLB4BjgKOZKhWjsVbkYqVSKnp6eU319fW8A"
    "126B/0KWZVRVJR6PEwgEOnp7e/uBOgBRsOBPJpPPtwnL8TWevJ5kJZHGwKDGodBcb8LrqULT"
    "NKqrq/H5fDcikchDubiSYRh8GJllaCrGdX8nRxsUMpsGv1eyPHoxwmkZzne2oigKQghTmYXV"
    "tTQvhxY40dbM8JdFUuk80z+iDE7M09l+nLfjMZIbuVJ7xYf+wRmEcpB344vYbRXEXn1nfSPH"
    "ylqWgdEl5iNpnr2f4fa1c3sLTP2MM/3HQl7VqHdXcudKGwMTvwg++IyWzyNJJr7Ore7fgcks"
    "MxfPIoBwdJVvkQ00IIeMcsAKQIV5y7Wu65TNoKPFg2QxY7ZacToqMVfIWGUJZ5UdxWZFViyc"
    "aXHv30HXycO0f/pLQtThtmk4LYKmGoXWJgcpoxK7HuPC2SMlAhKApmmFtjTu+t14s2M01lbx"
    "dCRDaFZwrNGDd3OSe34XQmx99zanpANd1/HW13L/Vhcfh0dZWlhHSIJ2jwPfTR82mw3DMHb8"
    "lwm4XK6dx6uXG0qES4ZtMu3sRSEe8ng8Ab0oczep6F4AJBKJx8DsP7f3ACwAunutAAAAAElF"
    "TkSuQmCC")
index.append('overview')
catalog['overview'] = overview

#----------------------------------------------------------------------
process = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAA2pJ"
    "REFUOI11k11oWwUYht/zl5NzcpaTk98lNI1JOc2kbbqxYqpTx2y6Ib2Y28hovRFkbFi88CLi"
    "TWWgFVRkFnH4AxWcd4PBmBtM98Na0+ykFdKltN3SLMsMC5u1PelfTtrkpF7YyhT9bt/vfS4+"
    "vgf4n2lrO/pVd/fgitkc6LNa/d3R6Md3+/uHbgGwP71H/FdZlqNnZTncL4ocaNoAQTDB4dgB"
    "j8eBROKnxLlzp48BePwPAMNIrXv3vv6DptVIq9UbCgScEEUBgmACxxnBMBSampzQdQax2Hs3"
    "8/lLPQDWqW1Aa2vfNUFobHe7na7jx19GJLIbsuwBz3PQ9Tp4ngVJEiAIwGDgbJnMxNj6+tqD"
    "vwGS1PpWIOB3nTx5CDabGYqSQzx+D4qShtttQUODHRRFwmrl0dX1HEtRjS+Mj98aoQDA5+v+"
    "Yteu51/t7d1PmUw8rl+fRSIxXk2nlfvx+NnY8nKV3rfvlWZRZMFxNESRxeamYIvHx5boUOjY"
    "18Fg1ymvV0Jjox03btxFKjVVHRv77rO1td8uAkhr2mqIYRhYLH/dolgsgaLq6OzsjdHBYOSU"
    "wyHA53NBVTVMTWUwOvrNkKYVzgNIS5Iv3Nf35tGdOzkwDIlCQcXs7CMUiypKJVUjS6UHv7As"
    "C12vY2mpDFUtQdMKSQCTZnNDx8DAt1d7el7yWSwG1Go6ZmYeYXIyB0WZWFWU4Q/I0dHvTwMk"
    "eJ7DxoYOSdpRYVm7LRzu/XRg4MvLBw92mAmiCkFg4fGIWF4uI5OZWcpmL3xULhev0LLcErRY"
    "eLAsDY5jcPjwi7Tff2YwEtnvcDqNMJkIGI0mWCwcdH0TLEtgbu7KcKmUuwSgSEWjb3/S0hLy"
    "u1wCGIaCKPJke3vQZLcbQNMEKpUqbDYTarU6RkayqNdpzM9XrA8fjg8DWKAmJn7+kedd4ebm"
    "0DM0TcDlEsFxJGiaxNzc70gmc0ilClhc3MCTJ6tIpXKYnk5rCwtT5wGo26/s2LPnjYuyvLvz"
    "xIlD9Y4OmZ6eLuD27fu4cyeHTOaeJor0Y1VdJMvlCpHPXx3StD8uA8g/JRPbZDQ6XvN63cZY"
    "7PNBSTIjkZhFMvnrWjZ74cP5+dw1ALUtf8pbMq38W0QDAN7pbHvnyJEzKwcOvL/I8653ATwL"
    "QNrKDQDo7cKfzfc7KseZc4UAAAAASUVORK5CYII=")
index.append('process')
catalog['process'] = process

#----------------------------------------------------------------------
pyshell = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAg5J"
    "REFUOI2tkk1I03EYxz+//1+2Of9L52r24uYaBSXdutShlDp0CYzohbpY0cFDL3gWi7oUQmAl"
    "QUJ18mAzmNjBoiDQELwoxWa25Qs5TciJNcZ0//+eLmrOF4roOT2/5/s83+/z8oP/aZebmsQX"
    "CuUex2Lib2sToP1PNdoKv86f+inHu7qU0dvLpoYGOsPhM39PENxZd/LiJbW5upr32QUGIxHu"
    "fpsS2/UrAtg2IlAAmsuVLOnvdxfriozA95kktnQaezqFVrmP2arDWIlJtWEHnndv3Ps/DzOj"
    "6xgTCey6RuZGI5mWR1imhZjmerWS99oDosE0EDXankhZX49UfB0Xd/dLAQIrcx1HDonn/p3f"
    "BHtLS+VBMLgc8L7tloovMfF8GBTN7xvIU3I6Q+6nrWv2IsDYoj9WNhQVfzwmRvM9AcqXF1bs"
    "el0+OWGpkpLn680EgLu1RQIjcfEORQVNhVdiWzpfiLP+at7sWn45z4qqjqJrimxfD+TkRB4a"
    "8OGqrQW4sFZaqdtbPw7kdo2PyI54XIDI6hTd650Oxj+J4+xpWRIvWMSMwvprjXangUIx392B"
    "7eCBSmUU5Z/KNJmfGMV96yZT7aHdwHDBMriQYd6yyClFYc05CmvOw6r7iwhZy2TuYTNAAhZ/"
    "4lIXuIwOtm87BlDsK2cuOYNud2DN/gCxIGvCyOgr4BSQWruHf7BfnoPGjBi/kJoAAAAASUVO"
    "RK5CYII=")
index.append('pyshell')
catalog['pyshell'] = pyshell

#----------------------------------------------------------------------
recent = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAUBJ"
    "REFUOI3t0j1rUwEUxvHfTW9rIHfRpd1cVBxc1MHsOhecHRXLLUVwMZ/AIXERQe4iCDppB8Gt"
    "Szct6AeILYKm+BKHXN9SE4K9xyFa7ezaBw6c4TmH/3nhQEl03ESOAhPkwkPkEh/wFW8lCpVj"
    "oKaukqspREcZozLi0YWIjn4M+9N8MowotyI+vox4tRpxO4tYuzqNtm4MuhF3FyIV6tI6i4+5"
    "cyQzl7FwlsmQeyc+mcvmLfU4vcLR81Pu8ZeTZjN2+u9SVKJic5Vmq7E3XP0wV7bmjQa8fsqZ"
    "FX6OmTnEuRaDLnTTvYK1pR3Xyr8Nxp+nBLyRzDRd/8H2OpPvHL/I/VNQ1Pat9EWb2cZ+gksb"
    "TdXuSOzyrcf7Z9RSyk3JDU+SaLv1zxUaErlQSFxGDwPh+W/PA1R/PEnL8v8/woH8Ah0VioYI"
    "i9+mAAAAAElFTkSuQmCC")
index.append('recent')
catalog['recent'] = recent

#----------------------------------------------------------------------
saveperspective = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAA1FJ"
    "REFUOI1tk21MU3cUxp97WwqVS1tx0mLvaKtrYUB94SbjRaUms8bICg1RXGVQZgwuTRYTY9Rt"
    "H5bgB8eWJbo4k82Ixrg4om4TMjuXofgWgcGQzW3oWlrWW0opb6Ug9NLy3xdrkHk+nl+eJ+fk"
    "PEeEl5TD4WBMJlMbgLU+n68NwEKC2e12hdls/qSubt9Ft3sgm36ZQSAQ2rR9e1lJcckWB4DV"
    "i5lKpTx+5MhHB+Ry9YpgMPh/g6qqqqK3bdWX4gugKcGXtEbDHkywmpoaQ17e+uq7937FiRPH"
    "Z8bGRhpEi8W1tbWlFdZdTrksXT4R6MZ7jkrKmM9yvb0Daes3cEM7dpTf6enpU3xw9OD1wUHX"
    "YQA/UQmxzWYzWa27WhgmXRYOdqC8YhNSGRVApnDt++sLvf3iWd4fSDl/7tTX8XjckdCJno1m"
    "sliqWhhGIRvx/oK3LEVIU4gQnxnH/a4xiKUsRcWmJU1nTj6amHpqWTy1qL6+vtJSvvu7ZakM"
    "M+q9jWx9OhixBJ2nnXAPzSGarkNf9yNsLlyBsq25K/sfPsnkQ1M/PjfQ6XT2ybCweWHqW7p6"
    "pwrK18zw97pBBiKYfPgPXP7HqHhnI4RoEvKNORSXv5LrevAHG5x42ppYoaO15XIr7x9VFL4R"
    "zaH4MDXaHYOWVUJwOvFvextyayth0EowO0PjVcPrFKeXFXj/fqLxBKeviUKhkADAPzI6dznW"
    "Gd1XrN8o176yCp6ms3DNj0NdtxdqHcFyaQCDvgguOYPgCrTYWqzZ0PXgd70YAD4GxDINe8P6"
    "4TE2Iy0V/BefgZ/mEW04A7YgC6zkL0TCEbCaLKz2/gZCa0CEOczH45zIDqRk6rTt7371ZalS"
    "SlMTpz/HnZ4+nJelRLVqCb2NW0VNDvO42A7I4UXptjy4e/ph29/o+ZOP1KBBldE0dPUbEnNe"
    "IeNlheSGSkpykpN9AN7UyunDraf2zgvDLeRm8yESfnyWdP3QSAwZjAdALgCgc49VID83k1hl"
    "CbmlTCbrkpICAAoTZ1JK8f6VT/cIZLaddFw9RrIzlrkAGJ4H4eSazGG/2UiaVVJiENEuANzS"
    "/1Az2N9YXzRnzFJ4AOhfgDlAkRG4KaeoCwDUS8WLImsGsHZp/z+rvEoNBUEjtAAAAABJRU5E"
    "rkJggg==")
index.append('saveperspective')
catalog['saveperspective'] = saveperspective

#----------------------------------------------------------------------
customcontrol = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAnFJ"
    "REFUOI2lkz2LlGcUhq/zPO/M7M7OTtaJu7K76kaIaKHiF341miqkCcTKdCkCAZv8AklnYyCE"
    "/IJU2vgDRLTSWIghqPiBijDqiBtdM7uTmffrnGPxjiJCIODdHLjhuTj34X7gIyWLe86cOXTg"
    "wPfmpZQlqApqoArFeGpB5VnlmQbSXL17+9fTyfbP1n118sSWmcEwZ5RBmsl4QlZAmsIogyyH"
    "USqMCiiKwMqa8fzx/NGkNVPLFucbqNUxAzNAhAjkpeMmpKWjFjBz1AT3QK4JT+4mZVKrRRbm"
    "W0y3m+9yvfin4Gq3YP9Sg2Hh7J1LAAc33B2AvIi0p4QEYOwBcOVRyo2e8kqFS/eWqU9McHip"
    "ya5ZYetcIC8M9yqelmUFeF+X7/RZbrSor7zi5f0uT/ol1xY3s2/bBn45FnEBNa+iooT3H68M"
    "lG7WYOOnkxw/OMfZU0f47eReFhrOlZ7y8/USLRXcMTVcPwAEgcs3e1x78JpRrUEQZ9/nTX78"
    "chPr17V43De0NMwqgOEVQEQA+KQZ+f3bjXRqgYcDuPg00H3tTE0Fts0KVktYHni1gTuokkSE"
    "GGPVKoFOu8a9Xp9HL4fs3zLN6tY2a5nTDhl/PHhO3LkeVRsfXqsjhlglcXeWOnW+2zkBqjzL"
    "RjRtggt/LTMzM81PX3ToNCEtDDOpADGJ0qi/3UBoTQZ+ODYLppz7c0BIc77ePk1/VLJn0yRm"
    "RhKdEAJEkaS/msvKmhAjaFk10VQxdw7NN8GURALukf5aiZkhAsNRxr+rwyixteObhc27jwdx"
    "MX3bKEOBCKjmgI47XoIXgFIUBX/3bp3////2P/QGWsxIJsvdP+sAAAAASUVORK5CYII=")
index.append('customcontrol')
catalog['customcontrol'] = customcontrol

